service: vanpd-TestNest1

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-northeast-1
  timeout: 10
  memorySize: 512
  stage: dev
  environment:
    TABLE_NAMES: vantest-tasks,vantest-users
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:CreateTable
        - dynamodb:PutItem
        - dynamodb:GetItem
        - dynamodb:UpdateItem
        - dynamodb:DescribeTable
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:DeleteItem
      Resource: arn:aws:dynamodb:${self:provider.region}:${aws:accountId}:table/*

    - Effect: Allow
      Action:
        - apigateway:GET
        - apigateway:POST
        - apigateway:PUT
        - apigateway:DELETE
      Resource: arn:aws:apigateway:${self:provider.region}::/*
  
functions:
  main:
    handler: dist/src/lambda.handler
    memorySize: 512
    timeout: 10
    events:
      - http:
          method: ANY
          path: /
          cors: true 
      - http:
          method: ANY
          path: '{proxy+}'
          cors: true 

resources:
  Outputs:
    ApiGatewayUrl:
      Description: "URL of the API Gateway"
      Value: !Sub "https://${ApiGatewayRestApi}.execute-api.${AWS::Region}.amazonaws.com/${self:provider.stage}/"
